CREATE TABLE users (
  id VARCHAR(255) NOT NULL ,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price DOUBLE NOT NULL
);